### ISSUE TITLE
Science Fiction caused crash

### ISSUE THREAD

**Issue by AvangionQ** [celebo/hakumod#7]
Will avoid using this card until this problem is patched.

09:03:45.797 INFO unlock.UnlockTracker> Already seen: conspire:PoisonWeapons
09:03:45.798 INFO unlock.UnlockTracker> Already seen: Haku:ScienceFiction
09:03:45.800 INFO unlock.UnlockTracker> Already seen: Exhume
09:03:53.186 INFO unlock.UnlockTracker> Already seen: Haku:ScienceFiction
09:03:53.323 INFO unlock.UnlockTracker> Already seen: ReplayTheSpireMod:Book of Names
09:03:53.323 INFO unlock.UnlockTracker> Already seen: infinitespire:TheBestDefense
09:03:53.326 INFO unlock.UnlockTracker> Already seen: hubris:Fate
09:03:55.188 INFO unlock.UnlockTracker> Already seen: ReplayTheSpireMod:Book of Names
09:03:55.322 INFO basemod.BaseMod> publish on post power apply
09:03:55.322 INFO basemod.BaseMod> powers modified
09:03:55.404 INFO basemod.BaseMod> publish on post power apply
09:03:55.405 INFO basemod.BaseMod> powers modified
09:03:55.538 INFO basemod.BaseMod> publishPostExhaust
09:03:55.638 INFO basemod.BaseMod> publish on post power apply
09:03:55.639 INFO basemod.BaseMod> powers modified
09:03:57.306 INFO basemod.BaseMod> publish on card use
09:03:57.307 INFO ThMod.ThMod> ThMod : Card used : ReplayTheSpireMod:Book of Names ; cost : 0
09:03:57.309 INFO ThMod.ThMod> typhoon-counter increased , now :11
09:03:57.957 INFO basemod.BaseMod> publish on post power apply
09:03:57.957 INFO basemod.BaseMod> powers modified
09:03:58.024 INFO basemod.BaseMod> publish on post power apply
09:03:58.024 INFO basemod.BaseMod> powers modified
09:03:59.408 INFO basemod.BaseMod> publish on card use
09:03:59.408 INFO ThMod.ThMod> ThMod : Card used : Haku:ScienceFiction ; cost : 0
09:03:59.411 INFO ThMod.ThMod> typhoon-counter increased , now :12
Exception: java.lang.NullPointerException
09:03:59.416 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
	at Hakumod.cards.Hakumen.fuumajin.ScienceFiction.use(ScienceFiction.java:49) ~[Hakumod.jar:?]
	at com.evacipated.cardcrawl.mod.hubris.patches.ZylophonePatch$MultiUse.use(ZylophonePatch.java:51) ~[Hubris.jar:?]
	at com.megacrit.cardcrawl.characters.AbstractPlayer.useCard(AbstractPlayer.java:1594) ~[?:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.getNextAction(GameActionManager.java:297) ~[?:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:151) ~[?:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:279) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2554) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:878) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:429) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
Controllers: removed manager for application, 0 managers active
Game closed.

**Comment by celebo** [comment]
Thanks for the message. I tested the card under different contexts and it indeed seemed to crash at random. I adjusted the code and it's working fine now. See 0.6.4 release: https://github.com/celebo/hakumod/releases/tag/0.6.4
